name: Build and Deploy backend

env:
  SERVICE_NAME: pick-perfect-api-image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: "${{ secrets.BACKEND_GCP_SA_KEY }}"
        project_id: ${{ secrets.BACKEND_PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Docker config
      run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
      working-directory: ./pick-perfect-backend

    - name: Build and push image
      run: |
          gcloud builds submit --tag ${{ secrets.BACKEND_DOCKER_IMAGE_URL }}:latest
      working-directory: ./pick-perfect-backend

    - name: Deploy to Cloud Run
      run: |
          echo SERVICE_NAME $SERVICE_NAME
          gcloud run deploy $SERVICE_NAME \
            --image ${{ secrets.BACKEND_DOCKER_IMAGE_URL }}:latest \
            --set-env-vars GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
            --platform managed \
            --allow-unauthenticated \
            --region us-central1 \
      working-directory: ./pick-perfect-backend

  
